import torch
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])
print(x)
print(x.shape)
print(y)
print(y.shape)
print(z)
print(z.shape)
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z]).shape)
print(torch.stack([x,y,z], dim=1))
print(torch.stack([x,y,z], dim=1).shape)
print()
print(torch.cat([x,y,z], dim=0))
print(torch.cat([x,y,z], dim=0).shape)

