import torch
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())
print()
bt = torch.ByteTensor([True,False,False,True])
ct = torch.CharTensor([True,False,False,True])
print(bt)
print(bt.long())
print(bt.float())
print()
print(ct)
print(ct.long())
print(ct.float())
print()
ft = torch.FloatTensor([True,False,False,True])
print(ft)
print(ft.long())